### ISSUE TITLE
Give the About or the Volunteer page a new header

### ISSUE THREAD

**Issue by Form-And-Function** [bit-by-bit-coding/bxb-website#33] opened 2020-06-20 16:48 UTC
I want each page to have its own header. It should be dynamic in some way and related to computer science.

**Comment by MoralCode** [comment] 2020-06-20 20:57
this might be nice to lump into the volunteer page redesign thats been happening

**Comment by MoralCode** [comment] 2020-06-23 19:38
closing as a duplicate of #34

**Closed by MoralCode** 2020-06-23 19:38 UTC
Labels: duplicate
